[package]
name = "huemanity"
version = "0.1.0"
authors = ["Finnkauski <iwiivi@gmail.com>"]
description="A simple wrapper and CLI for the Phillips Hue lights."
license="GNU GPLv3"
homepage="https://github.com/finnkauski/huemanity"
documentation=""
repository="https://github.com/finnkauski/huemanity"

[dependencies]
clap = "*"
reqwest = "*"
serde_json = "*"
serde = "*"
http = "*"
dotenv = "*"

[lib]
name = "huemanity"
path = "src/lib.rs"

[[bin]]
name = "huemanity"
path = "src/bin.rs"
